//! GENERATED BY scripts/sync-brand.mjs — DO NOT EDIT BY HAND.
//! Source of truth: brand.json at the repo root. Run `pnpm sync-brand`.
#![allow(dead_code)]

pub const APP_NAME: &str = "My App";
pub const SLUG: &str = "myapp";
pub const IDENTIFIER: &str = "com.example.myapp";
pub const DEVELOPER_NAME: &str = "Your Name";
pub const WEBSITE: &str = "https://example.com";
pub const REPOSITORY: &str = "https://github.com/your-username/my-app";
pub const DOWNLOAD_URL: &str = "https://github.com/your-username/my-app/releases/latest";
pub const LICENSE_URL: &str = "https://github.com/your-username/my-app/blob/main/LICENSE";
pub const COPYRIGHT: &str = "Copyright (c) 2026 Your Name";
pub const HOMEBREW_TAP: &str = "your-username/myapp";
pub const SETUP_SCRIPT_URL: &str = "https://raw.githubusercontent.com/your-username/my-app/main/setup/unix.sh";

/// App version, read from Cargo.toml at compile time.
pub const VERSION: &str = env!("CARGO_PKG_VERSION");
