/**
 * GENERATED BY scripts/sync-brand.mjs — DO NOT EDIT BY HAND.
 * Source of truth: brand.json at the repo root. Run `pnpm sync-brand`.
 */

export const brand = {
  "appName": "Tymar",
  "slug": "tymar",
  "identifier": "com.tonmoydeb.tymar",
  "version": "0.1.0",
  "developer": {
    "name": "Tonmoy Deb",
    "website": "https://tonmoydeb.com"
  },
  "repository": "https://github.com/tonmoydeb404/tymar",
  "downloadUrl": "https://github.com/tonmoydeb404/tymar/releases/latest",
  "licenseUrl": "https://github.com/tonmoydeb404/tymar/blob/main/LICENSE",
  "updaterEndpoint": "https://github.com/tonmoydeb404/tymar/releases/latest/download/latest.json",
  "scripts": {
    "setupSh": "https://raw.githubusercontent.com/tonmoydeb404/tymar/main/setup/unix.sh",
    "setupPs1": "https://raw.githubusercontent.com/tonmoydeb404/tymar/main/setup/windows.ps1",
    "uninstallSh": "https://raw.githubusercontent.com/tonmoydeb404/tymar/main/setup/unix-uninstall.sh",
    "uninstallPs1": "https://raw.githubusercontent.com/tonmoydeb404/tymar/main/setup/windows-uninstall.ps1"
  },
  "description": {
    "short": "Effortless time tracking for focused work.",
    "long": "Tymar is a minimal, powerful time tracking app for macOS, Windows, and Linux. Focus on your work while Tymar handles the rest."
  },
  "copyright": "Copyright (c) 2026 Tonmoy Deb",
  "homebrewTap": "tonmoydeb404/tymar"
} as const;

export type Brand = typeof brand;
