/**
 * GENERATED BY scripts/sync-brand.mjs — DO NOT EDIT BY HAND.
 * Source of truth: brand.json at the repo root. Run `pnpm sync-brand`.
 */

export const scriptUrls = {
  "setupSh": "https://raw.githubusercontent.com/your-username/my-app/main/setup/unix.sh",
  "setupPs1": "https://raw.githubusercontent.com/your-username/my-app/main/setup/windows.ps1",
  "uninstallSh": "https://raw.githubusercontent.com/your-username/my-app/main/setup/unix-uninstall.sh",
  "uninstallPs1": "https://raw.githubusercontent.com/your-username/my-app/main/setup/windows-uninstall.ps1"
} as const;
